MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: ''
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'resnest101'
  NO_MARGIN: True #soft margin
  DEVICE_ID: ('0')
  COS_LAYER: False  #arcface

INPUT:
  SIZE_TRAIN: [448, 448]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('veri')
  ROOT_DIR: ''

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 6
  NUM_WORKERS: 4

#
SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 90
  BASE_LR: 0.01
  IMS_PER_BATCH: 48
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  FP16: True
  MARGIN: 0.3



